skip_tags: true
platform:
  - x64
environment:
  matrix:
    - nodejs_version: 'Current'
    - nodejs_version: '8'
    - nodejs_version: '6'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
before_build:
  - node --version
build_script:
  - echo 'no build script'
test_script:
  - npm test
